### ISSUE TITLE
libmysqlclient.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hopewise** [customink/lamby#147]
I haven't change anything, but I started seeing this exception when deploy a new deployment:

```
Executing 'config/environment.Lamby.cmd' in function directory '/app'
--
Init error when loading handler
{
"errorMessage": "libmysqlclient.so.18: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.so",
"errorType": "Init<LoadError>",
"stackTrace": [
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
"/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'",
"/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'",
"/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'",
"/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<main>'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'",
"/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'",
"/usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'",
"/usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'",
"/usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'",
"/usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'",
"/usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'",
"/usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'",
"/app/config/application.rb:20:in `<top (required)>'",
"/app/config/environment.rb:2:in `require_relative'",
"/app/config/environment.rb:2:in `<top (required)>'",
"/usr/local/bundle/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:41:in `require'",
"/usr/local/bundle/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric.rb:41:in `run'",
"/usr/local/bundle/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:35:in `bootstrap_handler'",
"/usr/local/bundle/gems/aws_lambda_ric-2.0.0/lib/aws_lambda_ric/bootstrap.rb:8:in `start'",
"/usr/local/bundle/gems/aws_lambda_ric-2.0.0/bin/aws_lambda_ric:10:in `<top (required)>'",
"/usr/local/bundle/bin/aws_lambda_ric:23:in `load'",
"/usr/local/bundle/bin/aws_lambda_ric:23:in `<main>'"
]
}

```

Any idea ?

**Comment by metaskills** [comment]
I would start by removing bootsnap to see if that helps. If not, I would check your deploy/build process. Is the file not there, is the gem not there in the final image? Etc.

**Comment by hopewise** [comment]
Thanks @metaskills , removing `bootsnap` fixed the issue, it was confusing as it worked before.

**Comment by metaskills** [comment]
Right, likely still does, but may require a slightly diff implementation.
