### ISSUE TITLE
RuntimeError: Container does not exist. Cannot get logs for this container

### ISSUE THREAD

**Issue by amadeuspagel** [customink/lamby#42]
I get this error when running `./bin/deploy`.

I'm using cloud9 with ubuntu 18.04.

The full trace:

```
Starting Build inside a container
Building resource 'RailsFunction'

Fetching lambci/lambda:build-ruby2.5 Docker container image........................................................................................................................
Mounting /home/ubuntu/environment/readpaths as /tmp/samcli/source:ro,delegated inside runtime container
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.39.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 127, in cli
    mode,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 192, in do_cli
    artifacts = builder.build()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 104, in build
    lambda_function.runtime)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 195, in _build_function
    runtime)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 267, in _build_function_on_container
    container.wait_for_logs(stdout=stdout_stream, stderr=stderr_stream)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.39.0/libexec/lib/python3.7/site-packages/samcli/local/docker/container.py", line 197, in wait_for_logs
    raise RuntimeError("Container does not exist. Cannot get logs for this container")
RuntimeError: Container does not exist. Cannot get logs for this container
```

**Comment by metaskills** [comment]
Seems you are getting stuck at this line here? https://github.com/customink/lamby/blob/master/lib/lamby/templates/application_load_balancer/build#L8

I can also se you are using SAM v0.39.0, have you tried searching their issues for clues? See here https://github.com/awslabs/aws-sam-cli/issues?utf8=✓&q=is%3Aissue+Container+does+not+exist.+

I did a little bit and it seems this is an error local to your system, maybe Docker related. Most searches I saw mentioned windows which is not your issue... but can you dig around a bit in SAM's repo to see what you come up with?

**Comment by amadeuspagel** [comment]
I followed the sam tutorial and it worked:

```
#Step 1 - Download a sample application
sam init

#Step 2 - Build your application
cd sam-app
sam build
```

This is the output:

```
Building resource 'HelloWorldFunction'
Running RubyBundlerBuilder:CopySource
Running RubyBundlerBuilder:RubyBundle
Running RubyBundlerBuilder:RubyBundleDeployment

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```

So the problem is either with my app or lamby. I'll try to follow the lamby tutorial with a new app, to exclude the first possibility.

**Comment by metaskills** [comment]
Did you ever find out what this was?
