### ISSUE TITLE
Read only file system error

### ISSUE THREAD

**Issue by prcongithub** [customink/lamby#51]
I followed the quick guide to deploy a sample rails api app to AWS Lambda. When I hit the API, I am getting following error:

Anything I need to set to customize the tmp path? or am I missing anything?

Rails version: 6.0.3
Ruby Version: 2.7.1

```
 "errorMessage": "Read-only file system @ dir_s_mkdir - /var/task/tmp",
    "errorType": "Init<Errno::EROFS>",
    "stackTrace": [
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:211:in `each'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:599:in `generate_development_secret'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:421:in `secret_key_base'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:177:in `key_generator'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/globalid-0.4.2/lib/global_id/railtie.rb:28:in `block (2 levels) in <class:Railtie>'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:51:in `each'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `instance_exec'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `run'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'",
        "/var/lang/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'",
```

**Comment by metaskills** [comment]
Hey Prashant, thanks for using Lamby. I'm only a few days away from finishing the new getting started experience. So apologies if anything was difficult. It'll be better soon.

About your error. The only directory you can write to in Lambda is the `/tmp` directory. There are limitations on that too. 

* https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html

Whatever gem or code you have that is writing to your project's tmp will have to change the higher one. Do you know what code is doing that?

**Comment by prcongithub** [comment]
Hey Ken, its pure simple rails app with no other gems. When I ran it with RAILS_ENV=staging or RAILS_ENV=production, it worked, the problem appears only when I use development env.

**Comment by metaskills** [comment]
Ah! Thanks. Yea, I don't think you can deploy `development` to AWS. That mode does not do eager file loads, logging to STDOUT, etc.

**Comment by hopewise** [comment]
@metaskills I have a similar issue, but I am not using lamby, so this is a side question, how can I change rails tmp folder path to be for example `/tmp/rails.log` ?
