### ISSUE TITLE
undefined method sub for nil:NilClass

### ISSUE THREAD

**Issue by prcongithub** [customink/lamby#52]
Getting the below error for a POST request which generates below event:
```
## EVENT
{"queryStringParameters"=>{}, "multiValueHeaders"=>{"host"=>["api.***.com"], 
"content-type"=>["application/x-www-form-urlencoded"], 
"x-amzn-trace-id"=>["Root=1-5ebd4017-2bac93a418a717c03d540fd8"], 
"x-forwarded-port"=>["443"], "accept"=>["application/json"], "scope"=>["user"],
 "x-authenticated-userid"=>[" *******"], "x-forwarded-proto"=>["https", " https"], 
"content-length"=>["233"], "x-forwarded-for"=>["3.123.100.237"], "authorization"=>["Bearer *******"], "x-consumer-id"=>["7386304e-f7bd-4815-a086-030cfb0237fd"], "x-consumer-custom-id"=>["authoring_platform"], 
"x-consumer-username"=>["authoring_platform"], "x-authenticated-scope"=>["user"]}, "httpMethod"=>"POST", "pathParameters"=>{}, 
"path"=>"/industries/export_to_google_drive", "multiValueQueryStringParameters"=>{}, 
"headers"=>{"host"=>"api.****.com", "content-type"=>"application/x-www-form-urlencoded", "x-amzn-trace-id"=>"Root=1-5ebd4017-2bac93a418a717c03d540fd8", "x-forwarded-port"=>"443", 
"x-authenticated-scope"=>"user", "x-consumer-username"=>"authoring_platform", 
"x-authenticated-userid"=>"****", "x-forwarded-proto"=>"https", "content-length"=>"233", 
"x-forwarded-for"=>"3.123.100.237", "x-consumer-custom-id"=>"authoring_platform", 
"x-consumer-id"=>"7386304e-f7bd-4815-a086-030cfb0237fd", "authorization"=>"Bearer ****", "scope"=>"user", "accept"=>"application/json"}, "body"=>"X2NzcmY9eGw2cWJpcHUtM1VDanRteVBNb1h5QTg2UUN5alNId0J4V0tVJmluZHVzdHJ5JTVCZW1haWwlNUQ9cHJhc2hhbnQlNDBqb21iYXkuY29tJmluZHVzdHJ5JTVCZm9sZGVyJTVEJTVCdXJsJTVEPWh0dHBzJTNBJTJGJTJGZHJpdmUuZ29vZ2xlLmNvbSUyRmRyaXZlJTJGdSUyRjAlMkZmb2xkZXJzJTJGMEJ6Vjl6TjI1ak5XVlNXbHpkbVkzWjNsTVdFVSZjb250ZW50PWluZHVzdHJpZXMmYXV0aF90b2tlbj0=", 
"isBase64Encoded"=>true}
```
## Error Stacktrace
```
{
    "errorMessage": "undefined method `sub' for nil:NilClass",
    "errorType": "Function<NoMethodError>",
    "stackTrace": [
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/rack_http.rb:58:in `path_info'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/rack_http.rb:17:in `env_base'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/rack.rb:19:in `env'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/handler.rb:79:in `call_app'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/handler.rb:42:in `call'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby/handler.rb:7:in `call'",
        "/var/task/vendor/bundle/ruby/2.7.0/gems/lamby-2.0.0/lib/lamby.rb:21:in `handler'",
        "/var/task/app.rb:22:in `handler'"
    ]
}
```

## Lambda Handler
```
def handler(event:, context:)
  logger = Logger.new($stdout)
  logger.info('## ENVIRONMENT VARIABLES')
  logger.info(ENV.to_a)
  logger.info('## EVENT')
  logger.info(event)
  
  Rails.logger = logger
  Rails.application.config.logger = logger
  
  Lamby.handler $app, event, context, rack: :http
end
```

**Comment by metaskills** [comment]
Hey and thanks for using Lamby! Sorry for the slow reply. I'm looking at your event and I can't tell what rack method it is. I'm comparing it to these fixtures (https://github.com/customink/lamby/tree/master/test/test_helper/events) and not finding a match. Like if it was HTTP v1 I'd expect to see some `"version"=>"1.0", "resource"=>"$default"...` properties. Likewise that 1.0 would be a 2.0 for version two. I'm thinking you are using the older REST API? If so,

```ruby
Lamby.handler $app, event, context, rack: :rest
``` 

Would be what you need? Was there a reason you were not using HTTP API?

**Comment by prcongithub** [comment]
Hello Ken,
This request is generated by [Kong's](https://konghq.com/) Serverless AWS Lambda plugin. It is a REST API Request. I am not sure what you mean by older REST API? Has anything changed significantly in the REST API recently? 
Since changing the event structure was not possible for me, I forked the repo and changed just one line to fix it for my case:
[My Fork](https://github.com/prcongithub/lamby/commit/7321482ac484b211a005b436cd2639dc377959b8)

**Comment by metaskills** [comment]
Has anything changed significantly in the REST API recently?

YES! Late last year AWS rebased a new integration for API Gateway called HTTP API (https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/) the formats for the even pay load are entirely different. I think your issue is that your handler has `rack: :http` which uses that new method. I think you want this.

```ruby
Lamby.handler $app, event, context, rack: :rest
```

Which uses the older REST integration with API Gateway. Did you try that?

**Comment by prcongithub** [comment]
Will give it a try

**Comment by metaskills** [comment]
Closing for age. Let me know if you need to re-open. Thanks!

**Comment by prcongithub** [comment]
Setting ```rack: rest``` worked. Thanks!
