### ISSUE TITLE
JSON encoding error when serving images in HTTP rack

### ISSUE THREAD

**Issue by mtrolle** [customink/lamby#71]
When trying to serve a non-UTF8 file (e.g. a static image file) I get the following error:

```
mt$ ruby app.rb 
Traceback (most recent call last):
	9: from app.rb:23:in `<main>'
	8: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:43:in `to_json'
	7: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:22:in `encode'
	6: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:35:in `encode'
	5: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:110:in `stringify'
	4: from /var/lang/lib/ruby/2.7.0/json/common.rb:224:in `generate'
	3: from /var/lang/lib/ruby/2.7.0/json/common.rb:224:in `generate'
	2: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:57:in `to_json'
	1: from /var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:40:in `to_json'
/var/task/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:40:in `to_json': "\\x89" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

*Steps to reproduce:*
1. Add a PNG file to `app/assets/images/`
2. Call your lambda url `assets/my.png`
3. You should get a response like `{"message":"Internal Server Error"}`
4. Check your `CloudWatch` log to find an error message similar to above.

The way I understand Lamby it seems like the `app.rb#handler` function returns a Hash response ala: 
`{status: 200, headers: {...}, body: 'String content'}`.
Lambda then takes this respons and encode it to JSON (at least it's my assumption that it's Lambda doing this conversion?)

**Comment by metaskills** [comment]
Yup, there need to be hints for Base64 encoding for the API Gateway handoff to work. Does your app have `config.public_file_server.headers` set like we do in the starter?

https://github.com/customink/lamby-cookiecutter/blob/master/inserts/config/environments/production.rb#L7-L10

**Comment by mtrolle** [comment]
That solved my issue - another one for the #70 readme perhaps :)
